### PR TITLE
Added data with in-line folio information

### PR DESCRIPTION
**Pull request by sebastian-nehrdich**
There was a misunderstanding in our previous communication: The folio information, from my perspective, should not be stored in PA-files.json but as a property of each segmentnr in the respective files in segments/ and translated/. I fixed this with this PR.
The way I calculated the folio numbers this time (I hope I understood your approach correctly): If the segmentnr contains a ".", we take the value before the dot, otherwise we divide by 10 and round up: 
```
def get_folio(segment_nr):
    if len(segment_nr.split(':')) == 1:
        return ""
    number = segment_nr.split(':')[1]
    if "." in number:
        return number.split('.')[0]
    else:
        # return number divided by 10
        folio = str(int(int(number) / 10))
        return folio
    return ""
```

### CODE REVIEW

**Comment by ayya-vimala** [comment]
Hi Sebastian,

OK for the change in structure of the folio numbers. But the calculation is not entirely correct at least for Pali.

Basically what I did was:
- EBTs: use PTS numbers
- AN/SN/DHP - use sutta numbers
- commentaries: use every 10th number (as these don't have a number in the original files we just used consecutive numbers so they have no meaning in themselves but make it easier to jump to another section)

See here for code:
https://github.com/dharmamitra/dharmanexus-pali/blob/main/utils/convertnewformat.py

```
# Calculating Pali folios
                folios = []
                try:
                    currentfile = open(files_dir+'segments/'+file["filename"]+'.tsv','r', encoding='utf8')

                    segment_keys=[]
                    
                    for line in currentfile:
                        segnr = line.split()[0]
                        if not segnr == 'segmentnr':
                            segment_keys.append(segnr)

                    last_num = ''
                    for segment_key in segment_keys:
                        num = segment_key.split(":")[1].split(".")[0].split("_")[0]
                        if re.search(r"^(PA_anya|PA_tika|PA_atk)", segment_key):
                            if num.endswith('0') and num != last_num:
                                folios.append({"num": num, "segment_nr": segment_key})
                                last_num = num
                            else:
                                continue
                        else:
                            if num != last_num:
                                folios.append({"num": num, "segment_nr": segment_key})
                                last_num = num
```
So the key here is this one:
```
num = segment_key.split(":")[1].split(".")[0].split("_")[0]
```
It splits the number in three places. It first takes out the filename by splitting on `:` and using the rest.
Then the segment number is split on `.` and the first part used, then if there is a `_` then that is also split and the first part used. That way you filter out a lot of the segment numbers that are similar. So if the number is `1.1` or `1.2`, that only results in one folio number, namely for `1`.

If the resulting number ends in `0` for anya , tika or atk files, it uses that and discards the rest.

**Comment by sebastian-nehrdich** [comment]
Feel free to update this! I won’t have time to look into this before
Tuesday I think

**Comment by ayya-vimala** [comment]
I will have a look Tuesday my time.

**Comment by ayya-vimala** [comment]
Will be redoing this entirely into json as per our discussion so deleting this PR.

**Pull request closed without merging**
